
enum packet_type_enum
{
  _UNKNOWN_PACKET_TYPE = 0,
  _CO2_PACKET_TYPE,
  _HUMIDITY_PACKET_TYPE,
  _TEMPERATURE_PACKET_TYPE,
  _MULTIPLIER_PACKET_TYPE,
  _ZERO_POINT_CALIBRATION_TYPE,
  _ALTITUDE_CALIBRATION_TYPE,
};
